services:
  frontend:
    container_name: codeforge_frontend
    image: uqtri/codeforge_frontend:latest
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - default
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend:/app # Mount code vào container
      - /app/node_modules # Đảm bảo node_modules không bị ghi đè
  backend:
    container_name: codeforge_backend
    image: uqtri/codeforge_backend:latest
    build: ./backend
    ports:
      - "5000:5002"
    networks:
      - default
    volumes:
      - ./backend:/app # Mount code vào container
      - /app/node_modules # Đảm bảo node_modules không bị ghi đè
      - /test-cases:/test-cases
networks:
  default:
    driver: bridge
