services:
  frontend:
    container_name: codeforge_frontend
    image: uqtri/codeforge_frontend:dev
    build:
      context: ./frontend
      target: dev
      args:
        ENV: development
    ports:
      - "5173:5173"
      # - "80:80"
    networks:
      - default
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend:/app # Mount code vào container
      # - /app/node_modules # Đảm bảo node_modules không bị ghi đè
      # - frontend_node_modules:/app/node_modules

  backend:
    container_name: codeforge_backend
    image: uqtri/codeforge_backend:dev
    build:
      context: ./backend
      args:
        ENV: development
    command: node --inspect=0.0.0.0:9229 index.js
    ports:
      - "5000:5002"
      - "9229:9229"
    networks:
      - default
    # restart: always
    volumes:
      - ./backend:/app # Mount code vào container
      # - /app/node_modules # Đảm bảo node_modules không bị ghi đè
      - /app/node_modules # Đảm bảo node_modules không bị ghi đè
      # - backend_node_modules:/app/node_modules
      - ./test-cases:/test-cases
  redis:
    image: redis:latest
    container_name: codeforge_redis
    ports:
      - "6380:6379"
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  backend_node_modules:
# frontend_node_modules:
