services:
  frontend:
    container_name: codeforge_frontend
    image: uqtri/codeforge_frontend:latest
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - default
    volumes:
      - /etc/letsencrypt/live/codeforge.id.vn:/etc/letsencrypt/live/codeforge.id.vn
  backend:
    container_name: codeforge_backend
    image: uqtri/codeforge_backend:latest
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - default
networks:
  default:
    driver: bridge
