services:
  frontend:
    container_name: codeforge_frontend
    image: uqtri/codeforge_frontend:latest
    ports:
      - "5173:80"
    networks:
      - default
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
  backend:
    container_name: codeforge_backend
    image: uqtri/codeforge_backend:latest
    ports:
      - "5002:5002"
    networks:
      - default
networks:
  default:
    driver: bridge
