services:
  frontend:
    container_name: codeforge_frontend
    image: uqtri/codeforge_frontend:latest
    ports:
      - "5173:5173"
    networks:
      - default
    volumes:
      - /etc/certbot/live/codeforge.id.vn:/etc/certtbot/live/codeforge.id.vn

  backend:
    container_name: codeforge_backend
    image: uqtri/codeforge_backend:latest
    ports:
      - "5002:5002"
    networks:
      - default
networks:
  default:
    driver: bridge
