name: Github CI/CD
run-name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: tar the code
        run: tar -czf code.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-archive
          path: code.tar.gz
      - name: Deploy to Server
